// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: testpb.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	City          *string                `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_testpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TestMessage) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lower         *string                `protobuf:"bytes,1,req,name=lower" json:"lower,omitempty"`
	RepeatCount   *int32                 `protobuf:"varint,2,opt,name=repeat_count,json=repeatCount,def=1" json:"repeat_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TestRequest fields.
const (
	Default_TestRequest_RepeatCount = int32(1)
)

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_testpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{1}
}

func (x *TestRequest) GetLower() string {
	if x != nil && x.Lower != nil {
		return *x.Lower
	}
	return ""
}

func (x *TestRequest) GetRepeatCount() int32 {
	if x != nil && x.RepeatCount != nil {
		return *x.RepeatCount
	}
	return Default_TestRequest_RepeatCount
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_testpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{2}
}

func (x *TestResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type CacheStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         *int64                 `protobuf:"varint,1,opt,name=Bytes" json:"Bytes,omitempty"`
	Hits          *int64                 `protobuf:"varint,2,opt,name=Hits" json:"Hits,omitempty"`
	Gets          *int64                 `protobuf:"varint,3,opt,name=Gets" json:"Gets,omitempty"`
	Evicts        *int64                 `protobuf:"varint,4,opt,name=Evicts" json:"Evicts,omitempty"`
	Items         *int64                 `protobuf:"varint,5,opt,name=Items" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStatus) Reset() {
	*x = CacheStatus{}
	mi := &file_testpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStatus) ProtoMessage() {}

func (x *CacheStatus) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStatus.ProtoReflect.Descriptor instead.
func (*CacheStatus) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{3}
}

func (x *CacheStatus) GetBytes() int64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *CacheStatus) GetHits() int64 {
	if x != nil && x.Hits != nil {
		return *x.Hits
	}
	return 0
}

func (x *CacheStatus) GetGets() int64 {
	if x != nil && x.Gets != nil {
		return *x.Gets
	}
	return 0
}

func (x *CacheStatus) GetEvicts() int64 {
	if x != nil && x.Evicts != nil {
		return *x.Evicts
	}
	return 0
}

func (x *CacheStatus) GetItems() int64 {
	if x != nil && x.Items != nil {
		return *x.Items
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gets          *int64                 `protobuf:"varint,1,opt,name=gets" json:"gets,omitempty"`
	CacheHits     *int64                 `protobuf:"varint,12,opt,name=cache_hits,json=cacheHits" json:"cache_hits,omitempty"`
	Fills         *int64                 `protobuf:"varint,2,opt,name=fills" json:"fills,omitempty"`
	TotalAlloc    *uint64                `protobuf:"varint,3,opt,name=total_alloc,json=totalAlloc" json:"total_alloc,omitempty"`
	MainCache     *CacheStatus           `protobuf:"bytes,4,opt,name=main_cache,json=mainCache" json:"main_cache,omitempty"`
	HotCache      *CacheStatus           `protobuf:"bytes,5,opt,name=hot_cache,json=hotCache" json:"hot_cache,omitempty"`
	ServerIn      *int64                 `protobuf:"varint,6,opt,name=server_in,json=serverIn" json:"server_in,omitempty"`
	Loads         *int64                 `protobuf:"varint,8,opt,name=loads" json:"loads,omitempty"`
	PeersLoads    *int64                 `protobuf:"varint,9,opt,name=peers_loads,json=peersLoads" json:"peers_loads,omitempty"`
	PeerErrors    *int64                 `protobuf:"varint,10,opt,name=peer_errors,json=peerErrors" json:"peer_errors,omitempty"`
	LocalLoads    *int64                 `protobuf:"varint,11,opt,name=local_loads,json=localLoads" json:"local_loads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_testpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetGets() int64 {
	if x != nil && x.Gets != nil {
		return *x.Gets
	}
	return 0
}

func (x *StatusResponse) GetCacheHits() int64 {
	if x != nil && x.CacheHits != nil {
		return *x.CacheHits
	}
	return 0
}

func (x *StatusResponse) GetFills() int64 {
	if x != nil && x.Fills != nil {
		return *x.Fills
	}
	return 0
}

func (x *StatusResponse) GetTotalAlloc() uint64 {
	if x != nil && x.TotalAlloc != nil {
		return *x.TotalAlloc
	}
	return 0
}

func (x *StatusResponse) GetMainCache() *CacheStatus {
	if x != nil {
		return x.MainCache
	}
	return nil
}

func (x *StatusResponse) GetHotCache() *CacheStatus {
	if x != nil {
		return x.HotCache
	}
	return nil
}

func (x *StatusResponse) GetServerIn() int64 {
	if x != nil && x.ServerIn != nil {
		return *x.ServerIn
	}
	return 0
}

func (x *StatusResponse) GetLoads() int64 {
	if x != nil && x.Loads != nil {
		return *x.Loads
	}
	return 0
}

func (x *StatusResponse) GetPeersLoads() int64 {
	if x != nil && x.PeersLoads != nil {
		return *x.PeersLoads
	}
	return 0
}

func (x *StatusResponse) GetPeerErrors() int64 {
	if x != nil && x.PeerErrors != nil {
		return *x.PeerErrors
	}
	return 0
}

func (x *StatusResponse) GetLocalLoads() int64 {
	if x != nil && x.LocalLoads != nil {
		return *x.LocalLoads
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_testpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{5}
}

var File_testpb_proto protoreflect.FileDescriptor

var file_testpb_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x22, 0x35, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x49, 0x0a,
	0x0b, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x12, 0x24, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x01, 0x31, 0x52, 0x0b, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x79,
	0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x48, 0x69, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x65, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x47, 0x65, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x45,
	0x76, 0x69, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x45, 0x76, 0x69,
	0x63, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xf6, 0x02, 0x0a, 0x0e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x65, 0x74, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x68, 0x69, 0x74, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x66, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x12, 0x32, 0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x09, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x68, 0x6f,
	0x74, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x08, 0x68, 0x6f, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x61,
	0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x73, 0x4c, 0x6f, 0x61, 0x64, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x73,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x6f, 0x61,
	0x64, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xa7, 0x01, 0x0a, 0x0e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x54, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x09, 0x49, 0x6e, 0x69, 0x74, 0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x0d, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62,
})

var (
	file_testpb_proto_rawDescOnce sync.Once
	file_testpb_proto_rawDescData []byte
)

func file_testpb_proto_rawDescGZIP() []byte {
	file_testpb_proto_rawDescOnce.Do(func() {
		file_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_proto_rawDesc), len(file_testpb_proto_rawDesc)))
	})
	return file_testpb_proto_rawDescData
}

var file_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_testpb_proto_goTypes = []any{
	(*TestMessage)(nil),    // 0: testpb.TestMessage
	(*TestRequest)(nil),    // 1: testpb.TestRequest
	(*TestResponse)(nil),   // 2: testpb.TestResponse
	(*CacheStatus)(nil),    // 3: testpb.CacheStatus
	(*StatusResponse)(nil), // 4: testpb.StatusResponse
	(*Empty)(nil),          // 5: testpb.Empty
}
var file_testpb_proto_depIdxs = []int32{
	3, // 0: testpb.StatusResponse.main_cache:type_name -> testpb.CacheStatus
	3, // 1: testpb.StatusResponse.hot_cache:type_name -> testpb.CacheStatus
	5, // 2: testpb.GroupCacheTest.Initpeers:input_type -> testpb.Empty
	1, // 3: testpb.GroupCacheTest.Get:input_type -> testpb.TestRequest
	5, // 4: testpb.GroupCacheTest.GetStatus:input_type -> testpb.Empty
	5, // 5: testpb.GroupCacheTest.Initpeers:output_type -> testpb.Empty
	2, // 6: testpb.GroupCacheTest.Get:output_type -> testpb.TestResponse
	4, // 7: testpb.GroupCacheTest.GetStatus:output_type -> testpb.StatusResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_testpb_proto_init() }
func file_testpb_proto_init() {
	if File_testpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_proto_rawDesc), len(file_testpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testpb_proto_goTypes,
		DependencyIndexes: file_testpb_proto_depIdxs,
		MessageInfos:      file_testpb_proto_msgTypes,
	}.Build()
	File_testpb_proto = out.File
	file_testpb_proto_goTypes = nil
	file_testpb_proto_depIdxs = nil
}
